virtual_hosts:
  - domain: "localhost"
    port: 3080
    document_root: "./public"
    ssl_enabled: true
    ssl_redirect: true
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "test.local"
    port: 3080
    document_root: "./public/tech-support"
    ssl_enabled: true
    ssl_redirect: true
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "tech-support.local"
    port: 3080
    document_root: "./public/tech-support"
    ssl_enabled: true
    ssl_redirect: true
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "intranet.local"
    port: 3080
    document_root: "./public/intranet"
    ssl_enabled: true
    ssl_redirect: true
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"
