virtual_hosts:
  - domain: "localhost"
    port: 3080
    document_root: "./public/tech-support"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "test.local"
    port: 3080
    document_root: "./public/tech-support"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "intranet2.local"
    port: 3080
    document_root: "./public/intranet2"
    ssl_enabled: true
    ssl_redirect: true
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "intranet.local"
    port: 3080
    document_root: "./public/intranet"
    ssl_enabled: true
    ssl_redirect: true
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "ogolfen.z-sur.com.ar"
    port: 3080
    document_root: "./public/tech-support"
    ssl_enabled: true
    ssl_redirect: true
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"
