virtual_hosts:
  # Sitio principal en puerto estándar
  - domain: "localhost"
    port: 3080
    document_root: "./public/tech-support"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  # Mismo puerto que localhost (compartido)
  - domain: "electrosur.site"
    port: 3081
    document_root: "/home/jose/electrosur.site"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  # Mismo puerto que localhost (compartido)
  - domain: "www.electrosur.site"
    port: 3082
    document_root: "/home/jose/electrosur.site"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  # Mismo puerto que localhost (compartido)
  - domain: "electrosur.site"
    port: 3083
    document_root: "/home/jose/electrosur.site"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  # Puerto específico para admin (solo cuando SSL_ENABLED=false)
  - domain: "localhost"
    port: 3090
    document_root: "./public/intranet2"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  # Puerto específico para API (solo cuando SSL_ENABLED=false)
  - domain: "localhost"
    port: 3091
    document_root: "./public/intranet"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "7.4"
    php_pool: "www"

  - domain: "puntoa.z-sur.com.ar"
    port: 3083
    document_root: "./public/puntoa"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

    # Reglas de rewrite para aplicación MVC
    rewrite_rules:
      # Redirigir todas las peticiones a index.php si no son archivos o directorios reales
      - pattern: "^(.*)$"
        target: "/index.php"
        query_string: "url=$1"
        conditions:
          - type: "file_not_exists"
          - type: "dir_not_exists"
        flags: ["QSA", "L"]

  - domain: "pintorhogares.z-sur.com.ar"
    port: 3085
    document_root: "/home/jose/pintorhogares"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "tech-support.com.ar"
    port: 3086
    document_root: "/home/jose/tech-support"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "www.tech-support.com.ar"
    port: 3087
    document_root: "/home/jose/tech-support"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

  - domain: "desmalezado.z-sur.com.ar"
    port: 3088
    document_root: "./public/desmalezado"
    ssl_enabled: false
    ssl_redirect: false
    php_enabled: true
    php_version: "8.3"
    php_pool: "www"

    # Reglas de rewrite para aplicación MVC
    rewrite_rules:
      # Redirigir todas las peticiones a index.php si no son archivos o directorios reales
      - pattern: "^(.*)$"
        target: "/index.php"
        query_string: "url=$1"
        conditions:
          - type: "file_not_exists"
          - type: "dir_not_exists"
        flags: ["QSA", "L"]
